### ISSUE TITLE
Previsão para função cancelar nota?

### ISSUE THREAD

**Issue by gamadoleo** [deepcell/Nfsc21#10]
Existe alguma previsão referente a implementação do cancelamento de uma nota fiscal, se já iniciou essa parte pode nos dar um norte como podemos contribuir referente a essa parte?

**Comment by devasia2112** [comment]
Por gentizeza, leia a seguinte informação:

Substituição retificação de arquivos já escriturados

Somente é permitido o cancelamento antes da escrituração do documento fiscal e desde que não exista rotina específica (por exemplo, anulação de débitos).

No arquivo Mestre de Documento Fiscal, Campo 19 - Situação do documento, existe a possibilidade de preencher esse campo conforma regra abaixo: 

S - documento cancelado; 
N - documento não cancelado (situação normal). 

Caso se perceba que há documento a ser cancelado antes da escrituração, informe na CAT 79/2003 a situação do  documento cancelado e emita novo documento fiscal para sanar a irregularidade.

Caso o documento fiscal já tenha sido escriturado, **NÃO HÁ A POSSIBILIDADE DE CANCELAMENTO**. O débito é, portanto, devido e somente poderá ser restituído mediante procedimento específico previsto na legislação.


Em resumo se a NF já foi escriturada, não é possível cancelar. No entanto se a NF ainda não foi escriturada, é possível mudar a situação do documento apenas alterando o campo 19 no arquivo mestre para "S" no campo "documento cancelado".
