### ISSUE TITLE
Correção no script db_update_0.2

### ISSUE THREAD

**Issue by patrickelyoussef** [deepcell/Nfsc21#6]
Opa,

Estou testando seu código e percebi que ao rodar o script do mysql ele está acusando erro

Pra corrigir só colocar o ; no final das linhas 173, 135 e 80

Sou novo no github (então acho que o lugar correto seria aqui pra postar) e espero ter ajudado

Obrigado

**Comment by bruninn96** [comment]
Você conseguiu emitir notas com essa classe? Eu tentei aqui mas não consegui muito menos entender o funcionamento dela, poderia me dar uma força?

**Comment by devasia2112** [comment]
@bruninn96  o input dos dados pra classe como definidos aqui https://github.com/devasia2112/Nfsc21/blob/master/class/nfsc.21.class.php#L315
ja estao de acordo com a especificacao da NFSC, sendo assim a sua estrutura de dados precisa estar de acordo com esse padrao.

Se voce ja tiver a estrutura SQL pronta voce pode adaptar no seu desenvolvimento a partir desse script: https://github.com/devasia2112/Nfsc21/blob/master/nfsc.21.query.select.data.php

Se quiser apenas testar o funcionamento da classe, use esse outro script que ja oferece alguns dados em array:  https://github.com/devasia2112/Nfsc21/blob/master/nfsc.21.array.php 

Esses scripts servem apenas como sugestao para entender o uso, espero ter ajudado.
