### ISSUE TITLE
Erro ao executar 

### ISSUE THREAD

**Issue by jeanelvis** [deepcell/Nfsc21#8]
Amigo, ao executar o link sem banco de dados, ele me retorna este erro.
Fatal error: Uncaught Error: Call to a member function fetchColumn() on bool in /home/grupolara/public_html/n21/class/medoo.php:821 Stack trace: #0 /home/grupolara/public_html/n21/nfsc.21.query.select.data.php(129): medoo->max('Nfsc_21_Notas', 'num_nf', 'num_nf') #1 {main} thrown in /home/grupolara/public_html/n21/class/medoo.php on line 821

Poderia ajudar?

**Comment by devasia2112** [comment]
@jeanelvis A interface de consulta `nfsc.21.query.select.data.php` apenas funcionara se voce estiver conectado ao banco de dados, esse erro foi referente a chamada do PDO `fetchColumn()` que ocorre na classe medoo, isso ocorreu por que nao houve dados passados para a consulta quando a classe nfsc fez a chamada desse codigo:

```
$prox_nf = $database->max("Nfsc_21_Notas", "num_nf", [
	"periodo_apuracao" => $data_apuracao
]);

```
Eu vou fechar esse issue por que Isso nao e problema na classe nfsc, para testa-la eu recomendo usar esse script teste para o banco https://github.com/devasia2112/Nfsc21/blob/master/db/script_db_update_0.2.sql
