### ISSUE TITLE
erro operador  não suportado

### ISSUE THREAD

**Issue by gesse-fernandes** [deepcell/Nfsc21#9]
bom primeiramente gostaria de agradecer por ter compartilhado as informações necessárias para  gerar  nota fiscal a pós muito lida na documentação e também em seu código percebi que já esta quase tudo certo o ultimo detalhe está dando esse erro

Fatal error: Uncaught TypeError: Unsupported operand types: string + int in C:\xampp\htdocs\Nfsc21-master\Nfsc21-master\class\nfsc.21.class.php:1460 Stack trace: #0 C:\xampp\htdocs\Nfsc21-master\Nfsc21-master\nfsc.21.query.select.data.php(366): Nfsc_21->Item(NULL, NULL, 1, '1', '2104', '20210426', Array, '21', '4', Object(medoo)) #1 {main} thrown in C:\xampp\htdocs\Nfsc21-master\Nfsc21-master\class\nfsc.21.class.php on line 1460
porem já reescrevi  o código e até mudei mas pelo que vi a variavel  $this->num_ordem_item começa  uma string vazia assim = ''; e em seguida vi que incrementa com o valor 1 mas está dando esse erro percebi que antes desse erro e dessa operação você faz o mesmo e sim funciona mas ao chegar na linha 1460 ele não consegue progredir ai não sei se seria o banco de dados ou se está faltando mais alguma informação ou até mesmo dados inseridos.

**Comment by devasia2112** [comment]
Oi, voce esta emitindo mais de 1 item por documento fiscal?
Qual a versao do seu PHP?

Basicamente o erro diz que encontrou um problema no tipo do dado (datatypes), eu recomendo chamar a funcao `gettype()` na variavel que esta dando o problema para saber o tipo de dado, provavelmente esta como string quando precisaria ser um integer e como essa parte precisa ser incrementada (caso voce tenha mais de 1 item por documento fiscal), isso esta causando o problema. 
Tente fazer um `typecast` forcando a variavel ser um integer assim: `(int)$this->num_ordem_item` ou tente mudar a propriedade declarada inicialmente na linha 366 de: `public $num_ordem_item = ''; ` para: `public $num_ordem_item = 0; ` mas perceba que essa propriedade precisa ser do tipo numerico com 3 posicoes no momento que for escrever no arquivo para validar com a receita, voce pode criar um tratamento se decidir ir por esse caminho.

Nos meus testes funciona por que eu nao preciso gerar multiplos items por documento fiscal.

Me fala como resolveu isso por gentileza, assim se preferir mandar um pull request ou me dizer onde alterou eu posso atualizar a classe para beneficiar outros tambem.

**Comment by gesse-fernandes** [comment]
pronto acabei de encerrar os últimos ajustes tanto base de dados quanto mudando um pouco código pois tinhas alguns selects ou inserção faltando passagem de parâmetro vi tudo isso encerrei agora sim eu posso sim dar um pull request pra voce poder compreender a versão que o utilizo é a versão do php 8.
![localhost](https://user-images.githubusercontent.com/43449666/116292544-35737e00-a76c-11eb-8da4-451135cc3d26.PNG)
usei a classe do array foi lá onde alterei e só rescrevendo alguns erros básicos mas vou mandar pra voce poder ver a onde fui alterado.

**Comment by gesse-fernandes** [comment]
você pode me dar permissão pra mim poder enviar as alterações em parte pelo o git push

**Comment by devasia2112** [comment]
> você pode me dar permissão pra mim poder enviar as alterações em parte pelo o git push

sim, acabei de adicionar acesso a voce. Obrigado pela contribuicao.
